### ISSUE TITLE
Can you please check how to enable the autoplay functionality of Spotify within your card?

### ISSUE THREAD

**Issue by ovizii** [thlucas1/spotifyplus_card#12]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thlucas1/spotifyplus_card/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

When I check the settings of my Spotify app, I have enabled the “autoplay” feature so whenever I start playing a track, it will keep continuing with similar tracks. Or at least it seemed that way. I might be wrong, I'm just a very casual Spotify User. 

Could you add such an option to the card? Currently, if I start playing a track from the card, it will simply stop after that track. You could verify if I am doing something wrong by simply clicking on a single track and see if it keeps playing after the track.

### Describe the solution you'd like

Ideally there'd be an icon, right next to the pause, next track, repeat buttons like in this screenshot to enable and disable this feature.

![image](https://github.com/user-attachments/assets/1eb405e5-8802-4089-afd6-51ae0a4f5810)

### Describe alternatives you've considered

The workaround is to start playback from the android Spotify app and transfer it to your card.

### Additional context

No idea what else to add except maybe thanks for the awesome card and integration :-)

**Comment by thlucas1** [comment]
I was in the process of looking into this feature request when the Spotify Developer team unexpectedly removed the functionality that was required to make the feature work.  More details on that can be found [here](https://github.com/thlucas1/homeassistantcomponent_spotifyplus/wiki/Frequently-Asked-Questions#why-is-it-like-this).  

With that said, there is no way I can fulfill this request.
