### ISSUE TITLE
How about some more customization options for the search filters?

### ISSUE THREAD

**Issue by ovizii** [thlucas1/spotifyplus_card#16]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thlucas1/spotifyplus_card/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

I do not use have any interest in Audiobooks, Episodes, or Shows. 

![image](https://github.com/user-attachments/assets/ad8a0a29-5ce1-4d3b-8194-eb0c307e7bdf)

### Describe the solution you'd like

How about an option to decide what search filters get shown in the drop-down?

### Describe alternatives you've considered

Thanks for considering the feasibility of the suggestion.

### Additional context

Thanks for considering the feasibility of the suggestion.

**Comment by thlucas1** [comment]
Will be added with the next release.  New configuration option will be located under the "Search" options.

[ 1.0.9 ] - 2024/10/28

  * Added `searchMediaBrowserSearchTypes` config option to enable / disable selected search types.

**Comment by thlucas1** [comment]
Released v1.0.9, which fulfills this request.  Please re-open if it does not meet your needs.
