### ISSUE TITLE
Fire HD8 Table not rendering media lists (awsrossw)

### ISSUE THREAD

**Issue by thlucas1** [thlucas1/spotifyplus_card#24]
### Describe the issue

None of the sub sections work on the Fully Kiosk Browser - example the devices screen doesnt show anything but does report 7 items.

Devices and playlists not working on FireHD8 - Fully Kiosk browser
![IMG_8732](https://github.com/user-attachments/assets/467850b9-827f-409f-9d68-a888848
![IMG_8733](https://github.com/user-attachments/assets/ee84036c-86f0-4f5a-a60e-dd4c552439f6)
5340e)

Verify on Desktop - 
![Screenshot 2024-11-04 at 8 36 18 AM](https://github.com/user-attachments/assets/8028a724-88a4-45cf-b090-e51d126cead1)
![Screenshot 2024-11-04 at 8 36 27 AM](https://github.com/user-attachments/assets/d2a6ea17-17ca-424d-aff2-3072858e058e)

[@awsrossw](https://github.com/awsrossw)

**Comment by awsrossw** [comment]
Thanks. I also just updated to the APK of Fully Kiosk Browser vs the Play Store one - and got the same issue. good to hear you were able to reproduce on your side. 

Again Thanks for the bigger icons ! and the good looking card. Do you want my yaml config ?

**Comment by thlucas1** [comment]
@awsrossw 
Hi Ross - Just released v1.0.11 which should fix the media list issue on the Fire HD 8 device.  

Give it a try and let me know if it works or not; I think it will, but want to know for sure since I can only emulate the problem (don't have a physical Fire HD 8 device).

Thanks for your help with this - much appreciated.
Todd

[ 1.0.11 ] - 2024/11/04

  * Fixed a bug in all media list rendering controls that was causing the media list not to render for some browser types (Fire HD, iPad Air, etc).
  * Replaced all `lastupdatedon` properties with `date_last_refreshed` property that is populated by the spotifywebapiPython package.

**Comment by awsrossw** [comment]
Mic Drop!!! Boom! That fixed it.
![IMG_8735](https://github.com/user-attachments/assets/76292a4f-9edc-469a-9a51-52c0e5cdeb86)
![IMG_8737](https://github.com/user-attachments/assets/f969e175-0fdf-4a86-a055-8fa288dcea1c)
![IMG_8736](https://github.com/user-attachments/assets/7f5eaf7e-2819-4eb7-ad0c-ae3880cc916a)

Amazing !!!

**Comment by thlucas1** [comment]
Closing this issue, as it was fixed with v1.0.11 release.
