### ISSUE TITLE
Denon HEOS Devices not Connecting (@NathanCu @z3p337)

### ISSUE THREAD

**Issue by thlucas1** [thlucas1/spotifyplus_card#27]
### Describe the issue
Hey there Todd,
thanks for this awesome integration! Did you by chance ever try one of denons heos speakers? I guess they are similar to your bose soundtouchs. They are spotify connect only devices and seem to have a dynamic spotify device id. I just cant get them to respond reliably.  Everytime I leave home and use spotify within my car for example, home assistant completely loses the devices and the spotify integration only registers new spotify device ids, which are not translated to human readable names I gave them (e.g. kitchen, bathroom, etc).  As soon as I start to play some spotify songs on one of the speakers, the home assistant integration shows the correct names again.

I hoped, that SpotifyPlus would solve this and I think it really can.

I build a simple script that does the following:
```
action: spotifyplus.player_media_play_tracks
metadata: {}
data:
uris: spotify:playlist:4FhyjgN9pPxxxx
entity_id: media_player.spotifyplus_xxx
device_id: Badezimmer
```

However 9 out of 10 times I’m getting the following error. The 10th time it works flawlessly and the speaker starts playing:
```
Fehler: SAM0001E - An unhandled exception occured while processing method “GetInformation”. 
HTTPConnectionPool(host=‘192.168.1.32’, port=51952): Max retries exceeded with url: /zc/0?action=getInfo&version=2.7.1 
(Caused by NewConnectionError(‘<urllib3.connection.HTTPConnection object at 0x7f4d98f710>: Failed to establish a new connection: [Errno 111] Connection refused’))
```

The good thing is: It seems to know, how to address the speaker, even if home assistants spotify integration doesn't. It correctly resolves its ip address.

Do you have any advice maybe?

Thanks so much for the quick support! :slight_smile: Tried it out. It behaves the same. Sometimes it works, sometimes it doesn't and throws the “connection refused” error.
Seems like 50:50 success rate actually.
I tried to open the speakers ip-address with the port stated in the error (eg http://badezimmer:51952/) and get the same error. Chrome states “ERR_CONNECTION_REFUSED”.
The port that spotifyplus uses seems to be dynamic. Maybe denon heos only allows some of the used ports or something…

**Comment by awagner64404** [comment]
Hello, 

the integration is wounderful. I hope I can get it to work more often.

I get exactly the same error as described above with my denon AVR-X2600H DAB device. Some times it works but most of the time I get the error message:

Die Aktion spotifyplus/player_media_play_tracks konnte nicht ausgeführt werden. SAM0001E - An unhandled exception occured while processing method "GetInformation". HTTPConnectionPool(host='192.168.178.117', port=33805): Max retries exceeded with url: /zc?action=getInfo&version=2.7.1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f71954ae390>: Failed to establish a new connection: [Errno 111] Connection refused'))

Best regards

**Comment by Stefan765** [comment]
Hi, I get exactly the same error message as you! Is there already a solution?
Best regards

**Comment by thlucas1** [comment]
I am waiting on someone to run some Wireshark network traces for me on a Denon HEOS device (similar to yours maybe). After I get those, I should know a little bit better of what is going on with the Denon devices.

I don’t have any Denon devices to test with, so I am relying on others with Wireshark network tracing abilities to help me out.

**Comment by awagner64404** [comment]
I have conducted a capture, once starting via the phone and once starting via Home Assistant. How can I send these to you?
I would prefer not to make the network captures publicly available here.

Best regards.

**Comment by thlucas1** [comment]
@awagner64404 
Do you have an HA Community forum account?  If so, just post your above reply to the [SpotifyPlus Card Dashboard forum](https://community.home-assistant.io/t/spotifyplus-card-dashboard/795290/32) and I will send you a PM from there with my personal email address.  I really wish GH had a PM function.

Also, about the trace ... was the Denon device fully logged out when you started the trace?  If not, then you will want to re-run it after logging the Denon device out.  I basically need all activity between the Spotify player (desktop, or mobile) and the Denon device.  This should include at least 1 (or more) `getInfo` and `addUser` calls to the Spotify Connect Zeroconf web-server hosted by the Denon device.

A trace from HA to the device is not necessary - just need the one from an official Spotify App (desktop preferred if you have it, but mobile should be ok too I think).

I appreciate your help, and patience - thanks!
Todd

**Comment by awagner64404** [comment]
Your are welcome.

That's strange, as the error in GetInformation also appears when you only want to switch the title or album, even if a title was already playing and the device was logged in. A switch was hardly possible in that case.

Let me know if you need further information.
Andreas

**Comment by thlucas1** [comment]
Hi Andreas - I just pushed out SpotifyPlus v1.0.68 release. Can you give the new release a try with the Denon AVR scenario that we have been troubleshooting?

I added some logic in the underlying [spotifywebapiPython package](https://github.com/thlucas1/SpotifyWebApiPython) GetSpotifyConnectDevice method that first checks to see if the specified device is already in the device list. If found, then it will not disconnect / reconnect the device. Prior to this, it would always disconnect / reconnect the device. My thought there is that if the device is already in the list, then it should be connected and ready for immediate use.

I’m hoping that this fixes the Connection refused errors. My thought there is that the previous code was trying to reconnect too soon after issuing the disconnect, and the zeroconf web-service (running on the device) still had the session established with the disconnect call and could not establish a new session for the subsequent connect call (e.g. Connection refused) since the web-service only supports 1 connection at a time.

Please let me know, and thanks again for your help - much appreciated!

Todd

**Comment by awagner64404** [comment]
Hi Todd, as far as I’ve been able to test so far, everything is running smoothly. Great job, I'm happy :D

Andreas

**Comment by Stefan765** [comment]
Hi Todd, my Denon Avr 1600X is now running without any problems. Great work and thanks for your efforts!!! Best regards 
Stefan

**Comment by thlucas1** [comment]
I will close this issue for now, as this appears to be fixed.  Just re-open if necessary.
Thanks!
