### ISSUE TITLE
Ability to center the image/stretch to image resolution

### ISSUE THREAD

**Issue by hacshacdgacs** [thlucas1/spotifyplus_card#36]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thlucas1/spotifyplus_card/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Because I don't have the card in it's full resolution (I have it at 33 / 33) it's noticably off center since it starts from the left edge.

### Describe the solution you'd like

Having the ability to have the album art remain centered would help balance things and keep the album text in frame. 

### Describe alternatives you've considered

Making the card larger is a possibility but it then throws off the rest of the dashboard layout. 

### Additional context

Maybe having a fit/stretch to the resolution options? Would also allow people to have it as a banner type image if they don't mind the aspect ratio being wrong

**Comment by thlucas1** [comment]
Can you paste a screen capture of what the card looks like now in your dashboard?

**Comment by hacshacdgacs** [comment]
Not the best image as it's running on a tablet but it shows what I'm meaning, edit: the image never attached so here you go
![467479545_1121373949533142_2735556105365761724_n](https://github.com/user-attachments/assets/38c9d62f-bf0a-44aa-8695-a9df208403d4)

**Comment by thlucas1** [comment]
In your card configuration, what do you have specified for the `width:` and `height` attributes?
Have you tried the following?
```
width: fill
height: fill
```

**Comment by hacshacdgacs** [comment]
Yea I did, that makes the card oversized and pushes the other cards off the
screen

**Comment by hacshacdgacs** [comment]
I have 33 and 33 specified for both height and width

**Comment by thlucas1** [comment]
Understood.  I'm in the process of adding a new configuration variable for this.  It will default to "100% 100%", but will allow you to change to a valid CSS property (e.g. `contain`, `cover`, `100% 75%`, etc).  Will keep you posted on that.

**Comment by thlucas1** [comment]
Just released v1.0.26 of the card.  Give that a try, setting the [`playerBackgroundImageSize`](https://github.com/thlucas1/spotifyplus_card/wiki/Configuration-Options#playerbackgroundimagesize) configuration option.

[ 1.0.26 ] - 2024/12/24

  * Added `playerBackgroundImageSize` config option that specifies the size of the player background image.  Defaults to "100% 100%"; More info can be found on the [wiki docs](https://github.com/thlucas1/spotifyplus_card/wiki/Configuration-Options#playerbackgroundimagesize).

**Comment by hacshacdgacs** [comment]
The new card setting worked thanks, setting the option to contain, width to
fill and height to 40 made everything work for me

**Comment by thlucas1** [comment]
Awesome!  Would you mind sending another pic of the results?  Just want to compare the before and after.   NBD if not  - I just had a tough time wrapping me head around what you wanted it to look like.  LOL

**Comment by hacshacdgacs** [comment]
Here you go, 
![Screenshot_20241225_072316_Home Assistant](https://github.com/user-attachments/assets/a15f6573-ba96-4ba7-9e9d-95960bba0898)

I was just wanting to be able to either center it so I could so majority of the text but with the new setting I'm able to show the whole album art and keep it in the space I had created for it in the dashboard.

**Comment by thlucas1** [comment]
Now I understand.   At first I thought there was no way you were going to get the player track text to center under the date time above.   

Glad it worked out!  Enjoy.
